### ISSUE TITLE
--bargraph3d doesn't work with matplotlib==3.8.1

### ISSUE THREAD

**Issue by tatref** [louwrentius/fio-plot#127]
fio-plot is installed in a virtualenv with pip
```
(venv) [root@oel9- test]# python --version
Python 3.9.16

(venv) [root@oel9 test]# pip freeze
contourpy==1.2.0
cycler==0.12.1
fio-plot==1.1.9
fonttools==4.44.0
importlib-resources==6.1.1
Jinja2==3.1.2
kiwisolver==1.4.5
MarkupSafe==2.1.3
matplotlib==3.8.1
numpy==1.26.2
packaging==23.2
Pillow==10.1.0
pyan3==1.2.0
pyparsing==3.1.1
python-dateutil==2.8.2
six==1.16.0
zipp==3.17.0
```

Bench command used:
```
bench-fio -t file --size 1000M -o out --target bigfile.dd --iodepth 1 4  --numjobs 1 4 --runtime 20 --help
```

Error:
```
(venv) [root@oel9 test]# fio-plot -T title -i out/bigfile.dd/4k -r randread --bargraph3d -t lat
Traceback (most recent call last):
  File "/home/xxx/test/venv/bin/fio-plot", line 33, in <module>
    sys.exit(load_entry_point('fio-plot==1.1.9', 'console_scripts', 'fio-plot')())
  File "/home/xxx/test/venv/lib64/python3.9/site-packages/fio_plot/__init__.py", line 39, in main
    routing_dict[graphtype]["function"](settings, data)
  File "/home/xxx/test/venv/lib64/python3.9/site-packages/fio_plot/fiolib/bar3d.py", line 146, in plot_3d
    ax1.w_xaxis.set_ticks(float_x)
AttributeError: 'Axes3D' object has no attribute 'w_xaxis'
```

It's works fine with `matplotlib==3.7.0`

**Comment by louwrentius** [comment]
Thanks for the report, I'll look into it.

**Comment by louwrentius** [comment]
I've found some time to apply a fix. I've tested it on two machines. Both code and pypi is updated. 
![Uploading Screenshot 2023-12-10 at 01.37.30.png…]()
